### ISSUE TITLE
Add function to correct intensities in MRI slices with arbitrary orientations

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rcasero/gerardus#57]
```
Work to apply after Ben has aligned the images
```

Original issue reported on code.google.com by `rcas...@gmail.com` on 11 Mar 2015 at 10:31

**Comment by rcasero** [comment]
Chris, so that the issue doesn't get too old, could you push today the alpha version of your code to the scimat_lineintersection branch created by BenVillard, please? If the code is to not be public before publication, then instead commit to private-gerardus?

**Comment by rcasero** [comment]
Depends on #79
