### ISSUE TITLE
Create fake cine-MRI validation dataset from high resolution rat anatomical MRI

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rcasero/gerardus#58]
```
To validate Ben and Chris' alignment and intensity correction algorithms.
```

Original issue reported on code.google.com by `rcas...@gmail.com` on 11 Mar 2015 at 10:35

**Comment by rcasero** [comment]
High resolution anatomical MRI with 460 x 415 x 900 voxels  (resolution 2.539e-6 x 2.539e-6 x 2.441e-5) downsampled by a factor of 5.9173 in the Z-axis, to simulate the ratio in @BenVillard 's cine MRI data (resolution 1.40625e-3 x 1.40625e-3 x 8e-3).

**Comment by rcasero** [comment]
$ ./resize3DImage -o ~/Downloads/x008-z-downsample.mha --sigmaInVoxels --sigx 1 --sigy 1 --sigz 9 111 100 25 ~/data/X/008/MRI/Anatomical/im-cropped.mha

**Comment by rcasero** [comment]
Data and instructions given to @BenVillard

**Comment by rcasero** [comment]
Is this needed, or can it be closed?

**Comment by rcasero** [comment]
Abandoned
