### ISSUE TITLE
Fix ChangeLog

### ISSUE THREAD

**Issue by rcasero** [rcasero/gerardus#66]
ChangeLog has an entry for DiffusionMRIToolbox/fit_kurtosis_model.m, which is not in the repository.

We have instead DiffusionMRIToolbox/fit_DKI_model.m, but this one is not in the ChangeLog.

**Comment by Darryl-McClymont** [comment]
Fixed in latest commit (b461f869aaa1a4b6c0728e6bab36ad3eec024e33)
