### ISSUE TITLE
add scimat_lineintersection.m

### ISSUE THREAD

**Issue by ck3294** [rcasero/gerardus#72]
need to add scimat_lineintersection.m to the repository

**Comment by BenVillard** [comment]
I have created a branch called scimat_lineintersection. Users can checkout to this branch and commit to the function scimat_lineintersection there.

**Comment by rcasero** [comment]
well done. Now Chris and you can put your functions here, first as alpha
versions, if they are not ready.

Commit and push your daily changes until they are in a basic functioning
state (e.g. all dependencies are met, the functions run without giving
errors), and then merge the branch back to master, and delete it.

On 6 May 2015 at 16:50, Benjamin Villard <notifications@github.com> wrote:

> I have created a branch called scimat_lineintersection. Users can checkout
> to this branch and commit to the function scimat_lineintersection there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rcasero/gerardus/issues/72#issuecomment-99520000>.
>



-- 
Dr. Ramón Casero Cañas

Institute of Biomedical Engineering
Department of Engineering Science, University of Oxford
Old Road Campus Research Building, Headington
Oxford
OX3 7DQ
UK

tlf         +44 (0) 1865 617716
twitter   @Ramon_Casero
web      http://www.cs.ox.ac.uk/people/Ramon.CaseroCanas/

**Comment by rcasero** [comment]
branch merged with master
