### ISSUE TITLE
auto generated .DS_Store

### ISSUE THREAD

**Issue by BenVillard** [rcasero/gerardus#74]
Problem with the auto generated files on mac. 

OSX systems apparently creates automatically a "hidden file with a proprietary format created by OS X to store custom attributes of a folder" (Wiki)

However this gets conflicted with git as git thinks it is an untracked file. Should we remove it as suggested per this website?:

http://www.ladysign-apps.com/developer/remove-ds_store-files-from-my-git-repo-and-ignore-them/#.VUo_6dNViko

**Comment by rcasero** [comment]
You may not need to remove the .DS_Store files. The help for gitignore says that git will ignore "Patterns read from a .gitignore file in the same directory as the path, or in any parent directory"

http://git-scm.com/docs/gitignore

That is, I think if you put a .gitignore file in the top directory of gerardus (where the ChangeLog is), with the lines

__MACOSX
.DS_Store
*/.DS_Store
.DS_Store?


it will ignore those files in the whole tree.

**Comment by rcasero** [comment]
PS. I'm assuming that the files giving you trouble are .DS_Store, but you can check that with "git status", it will tell you which files are untracked in your local tree.
