### ISSUE TITLE
Replace improfile by interpolation for intensity_correct_LA

### ISSUE THREAD

**Issue by rcasero** [rcasero/gerardus#82]
Try finding coordinates of intersection points forming a line when to planes intersect (scimat_lineintersect).

Then, can we use interp3 to find the intensities of those intersection points? interp3 can extrapolate, so no problems with the convex hull, but we don't know whether grid coordinates need to be aligned to Cartesian planes.

**Comment by ck3294** [comment]
No longer needs to be done.
