### ISSUE TITLE
Build error (output/GMP_GERARDUS-test.cmake:16)

### ISSUE THREAD

**Issue by petteriTeikari** [rcasero/gerardus#83]
I am getting the following error:

<code>
[  8%] Performing test step for 'GMP_GERARDUS'
CMake Error at output/GMP_GERARDUS-test.cmake:16 (message):
  Command failed: 2
   'make' 'check'
  See also
    /<path>/gerardus/cpp/src/third-party/gmp-5.1.2/output/GMP_GERARDUS-test-*.log
make[2]: *** [../cpp/src/third-party/gmp-5.1.2/output/GMP_GERARDUS-test] Error 1
make[1]: *** [CMakeFiles/GMP_GERARDUS.dir/all] Error 2
make: *** [all] Error 2
</code>

When trying to build gerardus on 64-bit Ubuntu 14.04, after cloning it from here and having the dependencies met (if those are still valid: https://code.google.com/p/gerardus/wiki/BuildInstructions)

<code>
mkdir build; cd build; cmake ..; sudo make
</code>

What could be the solution?

**Comment by rcasero** [comment]
Hi petteriTeikari,

The Gerardus build is a bit temperamental. We use it internally, and can't provide a lot of support. It does build for me on 64-bit Ubuntu 14.04, though. We are half-migration from GoogleCode, so I'm not sure about the state of the build instructions. A few things that could help:

1) Do you need to build the project? Matlab functions don't need to be built. That's only if you want to use either a program or a mex function.

2) You shouldn't generally do "sudo make". It's better to "make" and then "sudo make install" if necessary, although Gerardus doesn't install to system areas, so you should be fine with "make install".

3) After your first "cmake ..", the build instructions say that you have to run a second "cmake ..". It seems that you only run one "cmake ..". Didn't the first "cmake .." run ask you to do a second "cmake .." too?

4) CMake is producing log files with the result of trying to build GMP_GERARDUS. The error message says that the log files are in gerardus/cpp/src/third-party/gmp-5.1.2/output/GMP_GERARDUS-test-.log and gerardus/cpp/src/third-party/gmp-5.1.2/output/GMP_GERARDUS-test. What do they say?

What are you interested in in particular?

Best regards,

Ramon.

**Comment by petteriTeikari** [comment]
Thanks for the reply @rcasero 

You are right that I was not looking for the whole toolbox. I was interested in the ItkToolbox and the image filters implemented there.

**Comment by rcasero** [comment]
For those ones, you need to build the project, I'm afraid, as it's a mex
function.

**Comment by rcasero** [comment]
Hi @petteriTeikari ,

I have tried building a clean project, and it works for me. Ubuntu 14.04 (Trusty).

Your error says that the linker cannot find 

Development/addedToPath/gerardus/cpp/src/third-party/gmp-5.1.2/libgmp.la

That's a file created by the build. After building, it appears in that location in my tree. Do you have it?

Could this be a permissions problem? E.g. you ran cmake or make with sudo, and it has created some directory owned by root that then when you try to make as a normal user it cannot write to?

**Comment by petteriTeikari** [comment]
I got now the following: 

<code>CMake Error: Problem with archive_read_open_file(): Unrecognized archive format
CMake Error: Problem extracting tar: /<path>/gerardus/cpp/src/third-party/boost_1_49_0.tar.gz
</code>

Which someone else got as well with CMake/Boost apparently: http://lists.boost.org/boost-users/2015/02/83802.php. The size of the .tar.gz was 6.9 kb so clearly there was some error with the download. I downloaded it manually and placed it to /gerardus/cpp/src/third-party/, and the cmake went through.

However I still get the same error, and did not run anything now with sudo, and I tried chmod 777 -R for gerardus and sudo make which gave the same error. And the libgmp.la is indeed found from the folder

**Comment by rcasero** [comment]
Sorry to be a pain, but could you try with a clean tree? It has to be a tree freshly cloned, otherwise there will be some files created on the cpp side that could interfere. And no sudo.

**Comment by petteriTeikari** [comment]
No worries @rcasero 

I got the following warnings during the first "cmake .." (and I had to manually copy+paste the downloaded boost library as the cmake for some reason still corrupted the download)

<code>
grep: /usr/local/MATLAB/R2013a/bin/mbuild: No such file or directory
</code>

<code>
-- WARNING: GMP found but could not compile print_GMP_version.cpp:
-- GMP_INCLUDE_DIR=/home/petteri/gerardusTemp/gerardus/cpp/src/third-party/gmp-5.1.2
-- GMP_LIBRARIES=/home/petteri/gerardusTemp/gerardus/cpp/src/third-party/gmp-5.1.2/output/lib/libgmp.so
-- GMP_LIBRARIES_DIR=/home/petteri/gerardusTemp/gerardus/cpp/src/third-party/gmp-5.1.2/output/lib
</code>

<code>
make[1]: *** No rule to make target `/home/petteri/gerardusTemp/gerardus/cpp/src/third-party/gmp-5.1.2/output/lib/libgmp.so', needed by `cmTryCompileExec2777755750'.  Stop.
make: *** [cmTryCompileExec2777755750/fast] Error 2
-- USING GMP_VERSION = 'unknown'
</code>

<code>
make[1]: *** No rule to make target `/home/petteri/gerardusTemp/gerardus/cpp/src/third-party/mpfr-3.1.2/output/lib/libmpfr.so', needed by `cmTryCompileExec149825891'.  Stop.
make: *** [cmTryCompileExec149825891/fast] Error 2
</code>

3 times: 

<code>
CMake Warning (dev) at cpp/src/third-party/CGAL-4.2/src/CMakeLists.txt:51 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "CGAL".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.
</code>

<code>
Call Stack (most recent call first):
  cpp/src/third-party/CGAL-4.2/src/CGAL_ImageIO/CMakeLists.txt:55 (collect_cgal_library)
This warning is for project developers.  Use -Wno-dev to suppress it.
</code>

<code>
-- Compiling Matlab function vmu2png.m...
-- ... compilation result: No such file or directory
</code>

Then on second run the same Matlab warning along wih the CMake Warnings (dev). The same <b>libgmp</b> error came which halted the make previously, along with the <b>libfmr</b> error.

But this time indeed the make <b>went through without any errors</b> so maybe there was just a problem with the <code>sudo</code>

**Comment by rcasero** [comment]
Hi Petteri,

Sorry for the slow reply, I was away on holiday.

It's great that it worked for you.

Checking yesterday, SourceForge is returning a webpage with an error
instead of the actual ITK tarball, and naming it like the tarball (if you
open the file with an editor, it's HTML). But it's possible to download it
manually from the ITK website.

The error seems to be all across SourceForge. Boost is also hosted there,
so you are probably getting the same problem.

The other warnings/errors are odd, but I cannot reproduce them, so it's
hard to debug them. If you manage to figure out what's wrong, I'd be
grateful to hear of any fixes!

Best regards,

Ramon.





On 6 July 2015 at 15:57, Petteri Teikari <notifications@github.com> wrote:

> No worries @rcasero <https://github.com/rcasero>
>
> I got the following warnings during the first "cmake .." (and I had to
> manually copy+paste the downloaded boost library as the cmake for some
> reason still corrupted the download)
>
>
> grep: /usr/local/MATLAB/R2013a/bin/mbuild: No such file or directory
>
>
> -- WARNING: GMP found but could not compile print_GMP_version.cpp:
> --
> GMP_INCLUDE_DIR=/home/petteri/gerardusTemp/gerardus/cpp/src/third-party/gmp-5.1.2
> --
> GMP_LIBRARIES=/home/petteri/gerardusTemp/gerardus/cpp/src/third-party/gmp-5.1.2/output/lib/libgmp.so
> --
> GMP_LIBRARIES_DIR=/home/petteri/gerardusTemp/gerardus/cpp/src/third-party/gmp-5.1.2/output/lib
>
>
> make[1]: *** No rule to make target /home/petteri/gerardusTemp/gerardus/cpp/src/third-party/gmp-5.1.2/output/lib/libgmp.so',
> needed bycmTryCompileExec2777755750'. Stop.
> make: *** [cmTryCompileExec2777755750/fast] Error 2
> -- USING GMP_VERSION = 'unknown'
>
>
> make[1]: *** No rule to make target /home/petteri/gerardusTemp/gerardus/cpp/src/third-party/mpfr-3.1.2/output/lib/libmpfr.so',
> needed bycmTryCompileExec149825891'. Stop.
> make: *** [cmTryCompileExec149825891/fast] Error 2
>
> 3 times:
>
>
> CMake Warning (dev) at cpp/src/third-party/CGAL-4.2/src/CMakeLists.txt:51
> (get_target_property):
> Policy CMP0026 is not set: Disallow use of the LOCATION target property.
> Run "cmake --help-policy CMP0026" for policy details. Use the cmake_policy
> command to set the policy and suppress this warning.
>
> The LOCATION property should not be read from target "CGAL". Use the
> target name directly with add_custom_command, or use the generator
> expression $, as appropriate.
>
>
> Call Stack (most recent call first):
> cpp/src/third-party/CGAL-4.2/src/CGAL_ImageIO/CMakeLists.txt:55
> (collect_cgal_library)
> This warning is for project developers. Use -Wno-dev to suppress it.
>
>
> -- Compiling Matlab function vmu2png.m...
> -- ... compilation result: No such file or directory
>
> Then on second run the same Matlab warning along wih the CMake Warnings
> (dev). The same *libgmp* error came which halted the make previously,
> along with the *libfmr* error.
>
> But this time indeed the make *went through without any errors* so maybe
> there was just a problem with the sudo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rcasero/gerardus/issues/83#issuecomment-118880522>.
>



-- 
Dr. Ramón Casero Cañas

Institute of Biomedical Engineering
Department of Engineering Science, University of Oxford
Old Road Campus Research Building, Headington
Oxford
OX3 7DQ
UK

tlf         +44 (0) 1865 617716
twitter   @Ramon_Casero
web      http://www.cs.ox.ac.uk/people/Ramon.CaseroCanas/

**Comment by rcasero** [comment]
Fixed
