### ISSUE TITLE
Generalize elastix_transf_imcoord2 to 3D points

### ISSUE THREAD

**Issue by rcasero** [rcasero/gerardus#85]
elastix_transf_imcoord2 is a Matlab function to apply a registration computed between two images to a point. Because of how transforms are defined in elastix/ITK, you have to apply to points the inverse transform you'd apply to the image.

Currently, it supports 2D points and 'SimilarityTransform'. Extend to support 3D points.

**Comment by ck3294** [comment]
almost ready to be committed

**Comment by ck3294** [comment]
Done. Will be committed

**Comment by rcasero** [comment]
Not gonna happen
