### ISSUE TITLE
Export private-gerardus svn to gitlab

### ISSUE THREAD

**Issue by rcasero** [rcasero/gerardus#88]
Instructions

http://doc.gitlab.com/ce/workflow/importing/migrating_from_svn.html

**Comment by rcasero** [comment]
Got account for GitLab

**Comment by rcasero** [comment]
Code migrated from subversion repository to gitlab repository. We need to check that everybody's papers have been migrated correctly.

**Comment by Darryl-McClymont** [comment]
There haven't been any problems with the migration for Jo, Nick, or me. Just waiting on @BenVillard, @ck3294 and @ezacur to update their papers.
