### ISSUE TITLE
Fix structure of RealignmentToolbox

### ISSUE THREAD

**Issue by rcasero** [rcasero/gerardus#94]
private-gerardus/matlab/RealignmentToolbox contains

RealignmentToolbox/
├── CorrNGFOF.m
└── Validation
    ├── CreateMesh.m
    ├── extractsysdia.m
    └── sortcontpnts.m

This doesn't look right. There shouldn't be a subdirectory there. CorrNGFOF.m looks more like a script than a function. Shouldn't this go in private-papers? Otherwise, we need help headers, etc.

And this code should probably go in the RegistrationToolbox, rather than have a new toolbox with only one function.

**Comment by BenVillard** [comment]
Good point. Had forgotten about that. I'll sort it out. Thanks!

On Wed, Oct 7, 2015 at 11:40 AM, Ramón Casero <notifications@github.com>
wrote:

> Assigned #94 <https://github.com/rcasero/gerardus/issues/94> to
> @BenVillard <https://github.com/BenVillard>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rcasero/gerardus/issues/94#event-428973584>.
>



-- 

Benjamin Villard
Doctoral Candidate in Biomedical Engineering
CDT in Healthcare Innovation
Institute of Biomedical Engineering
University of Oxford
Kellogg College
E: benjamin.villard@eng.ox.ac.uk
<https://owa.nexus.ox.ac.uk/owa/redir.aspx?C=070-DVKK50Gs_WWZtdMM6vN26m-MW9IIB0i5gCIEplvrNyjL5A_19PvufjJLPYKhaQCin0QElSs.&URL=mailto%3abenjamin.villard%40eng.ox.ac.uk>
T: +44 (0)7871540750

**Comment by rcasero** [comment]
Did it get sorted out? ;)

**Comment by rcasero** [comment]
To private
