### ISSUE TITLE
Bug in im2col3.m

### ISSUE THREAD

**Issue by Darryl-McClymont** [rcasero/gerardus#97]
This function breaks when the input image doesn't have the same dimensions in x and y. For example:
 a = im2col3(LL(1:20, 1:20, 1:25), [3 3 3], 'sliding');
^ this is fine.

When I call it with x and y of different sizes:
 a = im2col3(LL(1:20, 1:23, 1:25), [3 3 3], 'sliding');

I get this error:
Index exceeds matrix dimensions.

Error in im2col3 (line 108)
                    reshaped3D2D(blocksize_x*blocksize_y*(edgz-1)+1:blocksize_x*blocksize_y*edgz,bl)=...

**Comment by Darryl-McClymont** [comment]
I think you fixed this, right @NBasty ?

**Comment by NBasty** [comment]
Yes, on the 11th of May.
